# Generated by Django 3.0 on 2022-11-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_receptionist_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
