# Generated by Django 3.0 on 2022-11-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221112_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
