# Generated by Django 3.0 on 2022-11-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_report',
        ),
    ]
