# Generated by Django 3.0 on 2022-11-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
