# Generated by Django 3.0 on 2022-11-12 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=12)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('gender', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.BooleanField(default=0)),
                ('department', models.CharField(blank=True, default='', max_length=30)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
